version: '3.3'

services:
  sandbox:
    build:
      context: ./docker
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        PASSWORD: $PASSWORD
        REPO: $REPO
    container_name: vim_sandbox
    tty: true
    user: "${UID}:${GID}"
